FROM mysql:8.4.3

ARG MYSQL_ROOT_PASSWORD=rootpass
ARG MYSQL_DATABASE=app_db
ARG MYSQL_USER=app_user
ARG MYSQL_PASSWORD=app_pass
ARG MYSQL_ROOT_HOST=%

ENV MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} \
    MYSQL_DATABASE=${MYSQL_DATABASE} \
    MYSQL_USER=${MYSQL_USER} \
    MYSQL_PASSWORD=${MYSQL_PASSWORD} \
    MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}

EXPOSE 3306 33060
